# -*- coding: utf-8 -*-
"""Descriptive Statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqSo9IedqjBn4bQ84TKW0qwCmldEz1F_

Question no. 1 A bakery tracks the daily sales of muffins (in dozzens) over a week: {10,12,11,15,14,13,12}
What is the most representative value of their weekly sales, and why?

Answer: Data = 10,12,11,15,14,13,12
mean = 10+12+11+15+14+13+12/7
Means = 87/7 = 12.42
Arrange the value in ascending order
10,11,12,12,13,14,15
Median = 12
mode = 12
The most representative value of their weekly sales is 12 because the mean is near t0 12(12.42), mode and median of the data is 12.

Question no. 2 A teacher records the marks of her students in a short quiz{12,15,14,16,18,20,19}. What is the mean score, and what does it tell us about the class's performance?

Answer Mean = (12+15+14+16+18+20+19)/7
Mean =114/7 = 16.29
we can't tell about the class's performance because we do not know what is the maximum marks out of which the student got these marks.

Question no. 3 A store records the shoe sizes sold in one day: {7,8,9,8,8,10,7,9} What is the mode, and why is this informantion useful for the store manager?

Answer: Mode = 8
The important information for the store manager is that he has made shoe size 8 avalibility most in their store.

Question no. 4 A car dealer notes the prizes of used cars: {8000,9500,10200,11000,50000} Why is the median a better measure than the mean in this case? Calculate the median.

Answer: Arrange the numbers in ascending order
8000,9500, 10200, 11000, 50000
The median of the data is 10200
The reason of median is better than mean is in this case is their is an outlier(50000) in this data.

Question no. 5 A student times how long it takes to finish a puzzel each day: {25,30,27,35,40}.what does the range tell us about the variation in the student's puzzle-solving time?

Answer: Range = 40-25 = 15
The variation in the student's puzzle-solving time is 15.

Question no. 6 A farmer records the weekly weight of harvested apples (kg): {100,105,98,110,120}. Find the range. How can this help the farmer in planning his packaging?

Answer: Range: 120-98 = 22
This can help the farmer in packaging

Question no. 7 Two delivery companies track delivery delays (in minutes)
Company A: variance = 6
Company B: variance = 15
Which company is more consistent, and why?

Answer Company  A is more consistent because there is less variance than there is more consisent

Question no. 8 A finance Student compares the daily price fluctuation of two cryptocurrencies.
Coin A : Standard deviation = $30   
Coin B: Standard deviation = $ 120

Which coin is riskier to invest in, and why?

Answer: The Coin B is riskier to invest because Coin B the flactuation is high.

Question no. 9 A family records their monthly electricity usage(in kwh): {400, 420, 390, 450,410}
Find the mean and standard deviation. What do these values together tell you about the family's energy use pattern?

Answer: Mean = (400+420+390+450+410)/5
Mean = 414
find standard deviation first find variance
variance = 424
Standard deviation = 20.59
The family typically uses around 414 Kwh
Sd is 20.59
the Electricty usage is stable with some fluctuations

Question no. 10 A basketball player's points in 8 games are recorded: { 15,18,20,22,25,17,19,21}
Find the mean, median, mode, range and  standard deviation. What insights can these measures provide about the player's scoring performance?

Answer: Mean (15+18+20+22+25+17+19+21)/8
Mean = 19.62
Arrange the record in ascending order
15,17,18,19,20,21,22,25
 Median = 19.50
 Mode: There is no repeated values
 Range: 25-15 = 10
 Variance = 69.88/8
 8.74
 Standard deviation 2.96
 The player's scoring performance is score 19-20 point per game
 Low S.D 3 performace means consisent performance
 Stable and reliabe scores
"""